import { Button, Htag, Tag, Ptag } from '@/components';
import Head from 'next/head';



export default function Home(): JSX.Element {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link href="http://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap" rel="stylesheet" />

			</Head>
			<main >
				<>
					<Htag tag='h1'> Текст </Htag>
					<Button apperance='primary' arrow='right'>Кнопка</Button>
					<Button apperance='ghost' arrow='down'>Кнопка</Button>
					<Ptag size='l'>Обзац</Ptag>
					<Ptag>Обзац</Ptag>
					<Ptag size='s'>Обзац</Ptag>
					<Tag size='s'>Ghost</Tag>
					<Tag size='m' color='red'>Red</Tag>
					<Tag size='s' color='green'>Green</Tag>
					<Tag color='primary'>Primary</Tag>
				</>
			</main>
		</>
	);
}
